version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres
        networks:
            - laravel
        ports:
            - "10000:10000"

    postgres:
        image: postgres:16
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: laravel
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    node:
        image: node:20
        container_name: node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: sh -c "npm install && npm run dev"
        networks:
            - laravel

networks:
    laravel:

volumes:
    pg_data:
